# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Dateien die zu laden sind  
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# === BLOCK: INPUT_BOOLEAN_ALLE ===
# Zweck: Alle Boolean Helper an einer Stelle
# Status: ✅ Korrigiert - Duplicate Key behoben
# Erstellt: 2025-08-22
# Geändert: 2025-08-25 - Zusammengefügt

input_boolean:
  schlafbooster_aktiv:
    name: "Schlafbooster aktiv"
    icon: mdi:weather-windy
    initial: false
    
  bewaesserung_zeitplan_1_aktiv:
    name: "Zeitplan 1 aktiv"
    icon: mdi:calendar-check
    
  bewaesserung_zeitplan_2_aktiv:
    name: "Zeitplan 2 aktiv"
    icon: mdi:calendar-check
    
# === END BLOCK: INPUT_BOOLEAN_ALLE ===

# === BLOCK: TIMER_DACHLUKE_AUTO_CLOSE ===
# Zweck: Timer für automatisches Schließen der Dachluke nach variabler Zeit
# Status: ✅ Bereinigt
# Erstellt: 2025-08-23
# Abhängigkeiten: cover.strom_dachluke_unten_dachluke_bad_unten, input_number.dachluke_timer_minuten

timer:
  dachluke_auto_close:
    duration: "00:20:00"
    name: "Dachluke Auto-Close Timer"
    icon: mdi:timer-outline

input_number:
  dachluke_timer_minuten:
    name: "Dachluke Timer Minuten"
    min: 1
    max: 60
    step: 1
    initial: 20
    unit_of_measurement: "min"
    icon: mdi:timer-cog

# === END BLOCK: TIMER_DACHLUKE_AUTO_CLOSE ===

# === BLOCK: BEWAESSERUNG_HELPERS ===
# Zweck: Helper für Bewässerungs-Zeitpläne mit Smart Irrigation Support
# Status: ✅ Überarbeitet - Smart Irrigation Auto-Modus
# Erstellt: 2025-08-24
# Geändert: 2025-08-26 - Auto-Modus für Smart Irrigation

# Zeitplan-Steuerung
input_datetime:
  bewaesserung_start_zeit_1:
    name: "Bewässerung Startzeit 1"
    has_date: false
    has_time: true
    icon: mdi:clock-start
  
  bewaesserung_start_zeit_2:
    name: "Bewässerung Startzeit 2"
    has_date: false
    has_time: true
    icon: mdi:clock-start

# Tage-Auswahl für Zeitpläne - ERWEITERT für einzelne Wochentage + Auto
input_select:
  bewaesserung_zeitplan_1_tage:
    name: "Zeitplan 1 - Tage"
    options:
      - "Täglich"
      - "Mo"
      - "Di"
      - "Mi"
      - "Do"
      - "Fr"
      - "Sa"
      - "So"
      - "Auto"
    initial: "Auto"
    icon: mdi:calendar-week
    
  bewaesserung_zeitplan_2_tage:
    name: "Zeitplan 2 - Tage"
    options:
      - "Täglich"
      - "Mo"
      - "Di"
      - "Mi"
      - "Do"
      - "Fr"
      - "Sa"
      - "So"
      - "Auto"
    initial: "Auto"
    icon: mdi:calendar-week

# === END BLOCK: BEWAESSERUNG_HELPERS ===